[app]
debug = false
name = "Robot33 API"
version = "development"
description = """
## Description
This is the API for the Robot33 project.
"""

[llm_config.baidu_ernie]
qianfan_ak = "your ak"
qianfan_sk = "your sk"

[llm_config.openai_gpt]
openai_api_key = "api key"

[llm_config.fake]
responses = ["i am fake response"]

[security]
token = "default_token"

[db]
mongodb_url = "mongodb://localhost:27017"
mongodb_database = "robot33"
