[tool.poetry]
name = "robot33"
version = "0.1.0"
description = ""
license = "GPL-3.0-or-later"
authors = ["axiangcoding <axiangcoding@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.108.0"
loguru = "^0.7.2"
uvicorn = "^0.25.0"
langchain = "^0.0.354"
python-multipart = "^0.0.6"
python-jose = {extras = ["cryptography"], version = "^3.3.0"}
passlib = {extras = ["bcrypt"], version = "^1.7.4"}
pydantic = "^2.5.3"
pydantic-settings = "^2.1.0"
qianfan = "^0.2.5"
openai = "^1.6.1"
pymongo = "^4.6.1"


[tool.poetry.group.dev.dependencies]
pytest = "^7.4.4"
black = "^23.12.1"
flake8 = "^6.1.0"
httpx = "^0.26.0"
pytest-cov = "^4.1.0"
pytest-html = "^4.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120