name: "Lint"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name : Install Poetry
        run: |
          pipx install poetry
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Check poetry file and lock file
        run: |
          poetry check
          poetry lock --check
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint check with flake8
        run: |
          make check_style
          make lint
