name: "Lint"

on:
  pull_request:
    branches: [ "main" ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name : Install Poetry
        run: |
          pip install pipx
          pipx install poetry
      - name: Install dependencies
        run: |
          poetry install
      - name: Lint check with flake8
        run: |
          make lint
